# Generated by Django 5.2.7 on 2025-10-31 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_movimientoinventario_delete_movimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='giro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Giro del Proveedor'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Estado Activo'),
        ),
    ]
