# Generated by Django 5.2.7 on 2025-11-01 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_proveedor_giro_alter_proveedor_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='direccion',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Dirección Completa'),
        ),
    ]
