# Generated by Django 5.2.7 on 2025-11-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_proveedor_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Costo/Precio Unitario del Movimiento'),
        ),
    ]
