# Generated by Django 5.2.7 on 2025-11-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_movimientoinventario_precio_unitario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoinventario',
            name='referencia',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Destino de Salida'),
        ),
    ]
