# Generated by Django 5.2.7 on 2025-11-12 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_alter_movimientoinventario_referencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementoinventario',
            name='ubicacion',
            field=models.CharField(default='Almacén Zona A', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='referencia',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Destino/Referencia de Salida'),
        ),
    ]
