# Generated by Django 5.2.7 on 2025-10-30 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_acceso', models.IntegerField(choices=[(1, 'Administrador'), (2, 'Responsable'), (3, 'Jefe Almacén')], default=3, verbose_name='Nivel de Acceso')),
                ('numero_empleado', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de Empleado')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
